/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CustomData } from "./CustomData";
import { CustomDataCountArgs } from "./CustomDataCountArgs";
import { CustomDataFindManyArgs } from "./CustomDataFindManyArgs";
import { CustomDataFindUniqueArgs } from "./CustomDataFindUniqueArgs";
import { DeleteCustomDataArgs } from "./DeleteCustomDataArgs";
import { CustomDataService } from "../customData.service";
@graphql.Resolver(() => CustomData)
export class CustomDataResolverBase {
  constructor(protected readonly service: CustomDataService) {}

  async _customDataItemsMeta(
    @graphql.Args() args: CustomDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CustomData])
  async customDataItems(
    @graphql.Args() args: CustomDataFindManyArgs
  ): Promise<CustomData[]> {
    return this.service.customDataItems(args);
  }

  @graphql.Query(() => CustomData, { nullable: true })
  async customData(
    @graphql.Args() args: CustomDataFindUniqueArgs
  ): Promise<CustomData | null> {
    const result = await this.service.customData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CustomData)
  async deleteCustomData(
    @graphql.Args() args: DeleteCustomDataArgs
  ): Promise<CustomData | null> {
    try {
      return await this.service.deleteCustomData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
